const fs = require("fs-extra");
if (fs.existsSync("set.env")) {
  require("dotenv").config({
    'path': __dirname + "/set.env"
  });
}
const path = require("path");
const databasePath = path.join(__dirname, "./database.db");
const DATABASE_URL = process.env.DATABASE_URL === undefined ? databasePath : process.env.DATABASE_URL;
module.exports = {
  'session': process.env.SESSION_ID || "ANDBAD-BOT;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieUlnaU11Q0VUdjFUTGJDWGhpblZ0YUNYbmYvZDlGM0hTUG9OL3VtZGdHbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieVVndkdDbFhwRVd2TGlPUHpZREJWMzZSMnE2bkRIQ2ZkanBEY0tZTlZnYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIrTnN2UDA1bmZtNnErTmw4Y0FsdU9qL3ZMZUJIemVlVTlPUXUxaUZ3NTJvPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJSNXNxUlJJZzdONEMwS1JIS1hnQlZERC80NXFmVHFRNjU1N2dlTWM1QkRzPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjRFUkZwRjk4R0tYWDc5S1VZTXpjRU5zaUs3Q2lTc1AyNWRUeVBXNURUbU09In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ill1MnpHQW11bVluMnU0OHI0TXZvNDRJd0cydlpsOHc0aU96bitLSXFtaUU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOExPajhETjBnRkxUTk4wMk5mN3NaSVcrd0crTlZKc0szK1dJMnBhai9FRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUTBGV2xOUzZ1eFUxTWxBY2tueWFLNzJTZjdGVHdvbTR6VmtjZStNQlR4UT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InBqcnR5M0xlMlprYnBzZjIvNWZGL1FHWkI1WHp2djFURlR1Q0FjaW9pUjc1aUQyZE45Njg1QXNSWkF0SlBXZFZTQ2tJQnhIbHRIYnl4RkhLL21waURRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTk1LCJhZHZTZWNyZXRLZXkiOiJ6dTVnZEptWVg2U3FlT2RQM2lMRzhySzc0MGF6UkZYdW9CZUF5ZFk3Sk1VPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjQwNzg0ODU4NDMzQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkE1NzVCQ0Q4OEY0MkUzOTA0MzdDNjE2MTYwNkRDMjNBIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NDI3NDc1MDB9LHsia2V5Ijp7InJlbW90ZUppZCI6IjQwNzg0ODU4NDMzQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkNGMzREOUVDOTg2RjMyMjM0QzI5RDcyRjZEMTAxMzcwIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NDI3NDc1MDF9LHsia2V5Ijp7InJlbW90ZUppZCI6IjQwNzg0ODU4NDMzQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjBBQ0QxMzExODY2MDdGOUNGODg0RjdCNTNBQjU0QjkzIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NDI3NDc1MDN9LHsia2V5Ijp7InJlbW90ZUppZCI6IjQwNzg0ODU4NDMzQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjFDMjQ4NzEyRkY3NzNCRjJEMzU5QTk1RTU1MjM3MUI3In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NDI3NDc1MDN9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IkdibmJrOFpHU3pXdWtrT3VESkxJbWciLCJwaG9uZUlkIjoiMjQ0NWY3Y2QtMWNhMy00N2ZkLThhYWQtM2I2ZWQ1NzZiNjYwIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IldDVDk1emhqUTNLWklQWHQvM1JTRTFIMEtXOD0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJWZDVnQzdhNGtlS0ozNjdDUUR4RytRS1IrOWs9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiUTJDRTlWQTYiLCJtZSI6eyJpZCI6IjQwNzg0ODU4NDMzOjExQHMud2hhdHNhcHAubmV0IiwibmFtZSI6ImNvc21pbiJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTkNDdktzRkVOM3VnTDhHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiNGM4TnFwWjdLVU16c1JGYnFNaTFOZFpxMWkyZ3JMOTNUNFRNbVdQWjREbz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiRHZQelYyMXdCZWxFT2RtR0hYQXFZbHlwZ0VSMzVJR3F3OFcxU1BEN2JoY0tMdE1CMDdMRC8xTHgyQ0pBLzNRL3llRUkvNVVMT2grY1Y2Y21RVFJzQXc9PSIsImRldmljZVNpZ25hdHVyZSI6Ik5hVzRMTTlCSU90djBaZll1dzdQZWtTV21SK2xKV1NMQ0hMakptTDQ2eEphcm50QnQ3QTRWaUI4WFJrQmhZSUFsSWRtU29DUUpUY1ZOQUN4TDl4c0RBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiNDA3ODQ4NTg0MzM6MTFAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZUhQRGFxV2V5bERNN0VSVzZqSXRUWFdhdFl0b0t5L2QwK0V6SmxqMmVBNiJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc0Mjc0NzQ5OSwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFBcVAifQ==",
  'PREFIXE': process.env.PREFIX || '+',
  'OWNER_NAME': process.env.OWNER_NAME || "cosmin",
  'NUMERO_OWNER': process.env.NUMERO_OWNER || "0770811929",
  'AUTO_READ_STATUS': process.env.AUTO_READ_STATUS || "non",
  'AUTO_DOWNLOAD_STATUS': process.env.AUTO_DOWNLOAD_STATUS || "non",
  'BOT': process.env.BOT_NAME || "𝚫𝚴𝐃𝚩𝚫𝐃-𝚳D",
  'URL': process.env.BOT_MENU_LINKS || "https://i.imgur.com/L4U2K76.jpeg",
  'MODE': process.env.PUBLIC_MODE || 'public',
  'PM_PERMIT': process.env.PM_PERMIT || 'no',
  'HEROKU_APP_NAME': process.env.HEROKU_APP_NAME,
  'HEROKU_APY_KEY': process.env.HEROKU_APY_KEY,
  'WARN_COUNT': process.env.WARN_COUNT || '3',
  'ETAT': process.env.PRESENCE || '',
  'CHATBOT': process.env.PM_CHATBOT || 'no',
  'ANTICALL': process.env.ANTICALL || "non",
  'AUTO_REACT_STATUS': process.env.AUTO_REACT_STATUS || "yes",
  'DP': process.env.STARTING_BOT_MESSAGE || "yes",
  'ADM': process.env.ANTI_DELETE_MESSAGE || "yes",
  'DATABASE_URL': DATABASE_URL,
  'DATABASE': DATABASE_URL === databasePath ? "postgres://db_7xp9_user:6hwmTN7rGPNsjlBEHyX49CXwrG7cDeYi@dpg-cj7ldu5jeehc73b2p7g0-a.oregon-postgres.render.com/db_7xp9" : "postgres://db_7xp9_user:6hwmTN7rGPNsjlBEHyX49CXwrG7cDeYi@dpg-cj7ldu5jeehc73b2p7g0-a.oregon-postgres.render.com/db_7xp9"
};
let fichier = require.resolve(__filename);
fs.watchFile(fichier, () => {
  fs.unwatchFile(fichier);
  console.log("mise à jour " + __filename);
  delete require.cache[fichier];
  require(fichier);
});
